application: syndicate-signup
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

builtins:
- appstats: on
- admin_redirect: on
- deferred: on

handlers:
- url: /cron.*
  script: cron.app
  login: admin

- url: /.*
  script: syndicate_signup.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

